import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Facility Access</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Facility Access</h1>
          <h2>Set Appointment</h2>
          <iframe
            src='https://calendar.google.com/calendar/embed?src=a7f4549fe542d67b14dbca0debd3c0c3ac9a4686f8cfccb3cc9e0610f5cbcedc%40group.calendar.google.com&ctz=America%2FChicago'
            width='800'
            height='600'
            scrolling='no'
          ></iframe>
          <h2>Text us for access!</h2>
          <p>
            During your appointment window, send a text to{' '}
            <a href='sms:+13145302745;body=I have arrived'>314.530.2745</a> once
            you&apos;ve arrived.
          </p>
        </div>
      </main>
    </div>
  );
};

export default Home;
